### ISSUE TITLE
Unable to download file on IOS

### ISSUE THREAD

**Issue by DeveloperHitesh** [Amphiluke/cordova-plugin-save-dialog#4]
![IMG_20240606_184016](https://github.com/Amphiluke/cordova-plugin-save-dialog/assets/29274558/6cc59c7c-4dc7-4254-97f8-ef7862c6c2b4)

**Comment by DeveloperHitesh** [comment]
Please find above image in which added scenario.

**Comment by Amphiluke** [comment]
Hi,

If I get it correctly from the screenshot, the issue is not related to the plugin itself. It looks like the server responds with an [error code 406](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406) when the user tries to download the file. So the issue is either on the server side or probably the download request is malformed somehow.

Try downloading a file from an independent 3rd-party server (e.g. [httpbin.org](https://httpbin.org/#/Images)) and see if the problem persists or not.

**Comment by Amphiluke** [comment]
Feel free to reopen the issue if you can provide more detailed description and after ensuring that the problem is in the plugin itself, not in the server configuration or client-side download implementation.
