### ISSUE TITLE
Not able to download file again once we click on cancel option in save dialog in iOS.

### ISSUE THREAD

**Issue by Aishwarya-Karandikar-DFT** [Amphiluke/cordova-plugin-save-dialog#5]
![406_error_secure_message](https://github.com/user-attachments/assets/1ba98240-1731-48f0-ba6c-7644854dfbf4)
We had some observations based on previous response :
1. When we click on the cancel option in save dialog, the API call is getting stuck in between and we are not able to handle it to make new api call.
2. We are able to save the files again and again until we click on cancel button on save dialog. Once, cancelled we can't click or save the file and we receive 406 api error in logs.

**Comment by Amphiluke** [comment]
Please refrain from [duplicating](https://github.com/Amphiluke/cordova-plugin-save-dialog/issues/4) issues. Check out [this suggestion](https://github.com/Amphiluke/cordova-plugin-save-dialog/issues/4#issuecomment-2152783490) to see if it’s a server-side error or request corruption rather than the issue with the plugin itself.

**Comment by Aishwarya-Karandikar-DFT** [comment]
I have fixed this issue.
